#
# Profile.
#
cc_profile_show:
    pattern: /{_locale}/user/my/profile
    defaults: { _controller: CCDNUserProfileBundle:Profile:show, user_id: 0, _locale: en }

cc_profile_show_by_id:
    pattern: /{_locale}/user/{user_id}/profile
    defaults: { _controller: CCDNUserProfileBundle:Profile:show , user_id: 0, _locale: en }
        
cc_profile_edit:
    pattern: /{_locale}/user/my/profile/edit
    defaults: { _controller: CCDNUserProfileBundle:Profile:edit, user_id: 0, _locale: en }
