parameters:
    ccdn_user_user_admin.role.form.change.handler.class:    CCDNUser\UserAdminBundle\Form\Handler\RoleSetFormHandler
    ccdn_user_user_admin.role.form.change.type.class:       CCDNUser\UserAdminBundle\Form\Type\RoleType

services:
    role.form.change.handler:
        class:  %ccdn_user_user_admin.role.form.change.handler.class%
        arguments:  [@form.factory, @service_container, @user.manager]
    role.form.change.type:
        class:  %ccdn_user_user_admin.role.form.change.type.class%
        arguments:  [@doctrine]